version: '3.8'
services:
  assertion-da:
    image: ghcr.io/phylaxsystems/assertion-da/assertion-da:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp  # For temporary file mounting
      - assertion_data:/usr/local/assertions  # Named volume for persistent storage
    environment:
      - DA_DB_PATH=/usr/local/assertions
      - DA_CACHE_SIZE=1000000
      - DA_LISTEN_ADDR=0.0.0.0:5001
      - DA_LOG_LEVEL=${DA_LOG_LEVEL:-info}
      - DA_METRICS_ADDR=0.0.0.0:9002
      - DA_PRIVATE_KEY=${DA_PRIVATE_KEY?error}
    ports:
      - "${DA_PORT:-5001}:5001"
      - "${DA_METRICS_PORT:-9002}:9002"
    cap_add:
      - CAP_NET_BIND_SERVICE  # For container networking
      - CAP_DAC_OVERRIDE      # For file operations/mounting
    security_opt:
      - seccomp=unconfined   # Needed for container operations
    restart: unless-stopped

# Define the named volume
volumes:
  assertion_data:
    name: assertion_data  # Explicit name for the volume

secrets:
  private_key:
    external: true
